# -*- coding: utf-8 -*-
{
    "name": "MCP Server - Report Designer",
    "version": "16.0.1.0.0",
    "category": "Technical",
    "summary": "Expose GTECH Report Designer (reports.designer) reports over MCP "
    "as short-lived, downloadable PDF links.",
    "description": """
MCP Server - Report Designer
============================
Domain add-on for the **MCP Server (Core)** module. It surfaces the custom
reports built with the *Report Designer (XLSX, XLSM)* module
(``reports_designer`` / model ``reports.designer``) to MCP clients.

Unlike the standard QWeb-based domain add-ons, Report Designer reports are
generated by a dedicated engine that produces an XLSX workbook which is then
converted to PDF (via LibreOffice). Rather than re-rendering on demand, this
add-on generates the document up-front — as the authenticated ``res.users`` —
and hands the client a **tokenized, short-lived download URL** produced by the
core ``mcp.report.link`` facility (``mint_attachment``). The link streams the
stored PDF and expires after ``mcp_server.report_link_ttl`` (default 1h).

Tools
-----
* ``reports_designer.list_reports`` - list the available report definitions.
* ``reports_designer.get_report`` - full detail of one report incl. its
  parameters (code, type, whether required).
* ``reports_designer.generate_report`` - generate a report as PDF for a set of
  records / parameter values and return a short-lived download link.

All tools execute as the authenticated user; standard Odoo ACLs / record rules
apply to both the report definitions and the underlying business records.
""",
    "author": "Taj Singh <tjgurwara99@gmail.com>",
    "website": "https://github.com/tjgurwara99/odoo-mcp-new-architecture",
    "license": "OPL-1",
    "depends": ["mcp_server", "reports_designer"],
    "data": [],
    "assets": {},
    "installable": True,
    "application": False,
    "auto_install": False,
}
